version: '3.1'

services:
  app:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: passwordCPSC318
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: passwordCPSC318
      MYSQL_RANDOM_ROOT_PASSWORD: '!Secret_Password_CPSC318!'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
