---

- name: Update machine
  gather_facts: false
  hosts: localhost
  become: true
  tasks:

    - name: Update all packages
      package:
        name: '*'
        state: latest

    - name: Install yum-cron
      package:
        name: yum-cron
        state: latest

    - name: Edit /etc/yum/yum-cron.conf
      replace:
        path: /etc/yum/yum-cron.conf
        regexp: "apply_updates = no"
        replace: "apply_updates = yes"

    - name: Start and enable yum-cron
      service:
        name: yum-cron
        state: started
        enabled: yes
